---
- name: Deploy JPetStore Docker container
  hosts: "{{ target_host | default('localhost') }}"
  become: "{{ use_sudo | default(true) }}"
  vars:
    docker_image: "khaledmohamed447/jpetstore-app"
    docker_tag: "{{ docker_tag | default('latest') }}"
    container_name: "jpetstore-app"
    exposed_port: "8081"

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add Jenkins user to Docker group (for local deployment)
      ansible.builtin.user:
        name: "{{ ansible_user | default('jenkins') }}"
        groups: docker
        append: yes
      when: target_host == "localhost" and not use_sudo | bool

    - name: Log in to Docker Hub
      ansible.builtin.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
      vars:
        dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
        dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"
      when: dockerhub_username != "" and dockerhub_password != ""

    - name: Stop and remove existing container if it exists
      ansible.builtin.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Run JPetStore container
      ansible.builtin.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}:{{ docker_tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ exposed_port }}:8081"
        detach: yes
